
services:
  wordpress:
    image: wordpress
    container_name: wp
    ports:
      - "80:80"
    volumes:
      - /efs/site:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${db_host}
      WORDPRESS_DB_USER: ${db_user}
      WORDPRESS_DB_PASSWORD: ${db_pass}
      WORDPRESS_DB_NAME: ${db_name}
    restart: unless-stopped                          